### ISSUE TITLE
Support VS2022

### ISSUE THREAD

**Issue by A9G-Data-Droid** [dev-maxima/nsis-extension#20]
Running `bizeta.nsis-task-2.0.1.vsix` results in a clear error that says it's not compatible with the latest version of Visual Studio:

```
9/30/2022 1:56:47 PM - Found installed product - Visual Studio Community 2022
9/30/2022 1:56:47 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by A9G-Data-Droid** [comment]
Nevermind. This isn't even a Visual Studio Extension. DERP
